//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppKit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebAppKit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //System Frame Prototype
        ///function Frame(fname){
        ///	this.Name = fname;
        ///	window[fname] = this.Name;
        ///}
        ///Frame.prototype.Location = &quot;about:blank&quot;;
        ///Frame.prototype.Name = &quot;&quot;;
        ///Frame.prototype.Title = &quot;undefined&quot;;
        ///Frame.prototype.Height = 640;
        ///Frame.prototype.Width = 640;
        ///Frame.prototype.MaximiseBox = true;
        ///Frame.prototype.MinimiseBox = true;
        ///Frame.prototype.ControlBox = true;
        ///Frame.prototype.Opacity = 100;
        ///Frame.prototype.ShowInTaskbar = true;
        ///Frame.prototype.Load = function(stdout){
        ///	if(this.Name != [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AppKit {
            get {
                return ResourceManager.GetString("AppKit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var Directory = function(){};
        ///Directory.Exists = function(dir,out){
        ///	var arg = [];
        ///	arg[&quot;path&quot;] = dir;
        ///	Framework.Query(&quot;fm_DirExists&quot;,arg,out);
        ///};
        ///Directory.Create = function(dir,out){
        ///	var arg = [];
        ///	arg[&quot;path&quot;] = dir;
        ///	Framework.Query(&quot;fm_DirCreate&quot;,arg,out);
        ///};
        ///Directory.Delete = function(dir,out){
        ///	var arg = [];
        ///	arg[&quot;path&quot;] = dir;
        ///	Framework.Query(&quot;fm_DirDelete&quot;,arg,out);
        ///};
        ///Directory.GetFiles= function (dir,out){
        ///	var arg = [];
        ///	arg[&quot;path&quot;] = dir;
        ///	Framework.Query(&quot;fm_GetFiles&quot;,arg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AppKit_IO {
            get {
                return ResourceManager.GetString("AppKit_IO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
